"""add language to posts

Revision ID: 866c9618bdf7
Revises: 7b0ebedaaad0
Create Date: 2020-01-09 13:32:35.173503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866c9618bdf7'
down_revision = '7b0ebedaaad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('Language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'Language')
    # ### end Alembic commands ###
